/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

/**
 *
 * @author Usuario
 */
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pkgModelo.clsMetodo;
import pkgModelo.clsSeleccionFutbol;

public class frmBuscar extends javax.swing.JFrame {

    private static frmBuscar instancia;

    /**
     * Creates new form frmBuscar
     */
    public frmBuscar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    public static frmBuscar getInstance() {
        if (instancia == null) {
            instancia = new frmBuscar();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloBuscar = new javax.swing.JLabel();
        lblIdBuscar = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        txtApellidoBuscar = new javax.swing.JTextField();
        lblApellidoBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCoincidencia = new javax.swing.JList();
        lblCoincidencia = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        mnBuscar = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        mnOpciones = new javax.swing.JMenu();
        mnOpBuscar = new javax.swing.JMenuItem();
        mnOpMostrar = new javax.swing.JMenuItem();
        mnCrear = new javax.swing.JMenu();
        mnCrearFut = new javax.swing.JMenuItem();
        mnCrearEnt = new javax.swing.JMenuItem();
        mnCrearMas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        lblTituloBuscar.setText("Buscar Selección Futbol");

        lblIdBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblIdBuscar.setText("Id:");

        txtIdBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        txtApellidoBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblApellidoBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblApellidoBuscar.setText("Apellido:");

        btnBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPrincipal.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnPrincipal.setText("<-- Menu Inicial");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstCoincidencia);

        lblCoincidencia.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        lblCoincidencia.setText("Coincidencias Busqueda por Apellido:");

        lblMensaje.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCoincidencia)
                                    .addComponent(lblTituloBuscar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblApellidoBuscar)
                                    .addComponent(lblIdBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdBuscar)
                                    .addComponent(txtApellidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBuscar)
                .addGap(21, 21, 21)
                .addComponent(lblCoincidencia)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnPrincipal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdBuscar)
                            .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoBuscar)
                            .addComponent(txtApellidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        mnArchivo.setText("Archivo");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(mnSalir);

        mnBuscar.add(mnArchivo);

        mnOpciones.setText("Opciones");

        mnOpBuscar.setText("Buscar");
        mnOpBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpBuscarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpBuscar);

        mnOpMostrar.setText("Mostrar Todo");
        mnOpMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpMostrarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpMostrar);

        mnBuscar.add(mnOpciones);

        mnCrear.setText("Crear");

        mnCrearFut.setText("Crear Futbolista");
        mnCrearFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearFutActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearFut);

        mnCrearEnt.setText("Crear Entrenador");
        mnCrearEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearEntActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearEnt);

        mnCrearMas.setText("Crear Masajista");
        mnCrearMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearMasActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearMas);

        mnBuscar.add(mnCrear);

        setJMenuBar(mnBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        clsMetodo metodo = clsMetodo.getInstance();
        frmEditar editar = frmEditar.getInstance();

        lblMensaje.setText(null);
        if (txtIdBuscar.getText().isEmpty() && txtApellidoBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Porfavor Diligencia uno de los 2 Campos");
        } else {
            for (clsSeleccionFutbol persona : frmPrincipal.SeleccionFutbol) {
                if (persona.getId().equals(txtIdBuscar.getText())) {
                    this.setVisible(false);
                    editar.setVisible(true);
                    metodo.buscarContacto(persona);
                } else if (persona.getApellido().toLowerCase().equals(txtApellidoBuscar.getText().toLowerCase())) {
                    lstCoincidencia.setModel(metodo.ListarCoincidencia());
                    lblMensaje.setText("Escriba el Id de la Persona que esta Buscando en la Casilla Correspondiente");
                } else {
                    lblMensaje.setText("No se Encontraron Coincidencias");
                }
            }
        }
        txtIdBuscar.setText(null);
        txtApellidoBuscar.setText(null);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        // Volver Menu Principal:
        frmPrincipal principal = frmPrincipal.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // Salir Programa:
        this.dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnOpBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpBuscarActionPerformed
        // Buscar:
        clsMetodo metodo = clsMetodo.getInstance();

        this.lstCoincidencia.setModel(metodo.Listar());
        this.setVisible(true);
    }//GEN-LAST:event_mnOpBuscarActionPerformed

    private void mnOpMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpMostrarActionPerformed
        // mostrar Todo:
        pkgVista.frmMostrar mostrar = frmMostrar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            frmMostrar.lstMostar.setModel(metodo.Listar());
            mostrar.setTitle("Mostrar Selección");
            mostrar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }
    }//GEN-LAST:event_mnOpMostrarActionPerformed

    private void mnCrearFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearFutActionPerformed
        // Crear Futbolista:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Futbolista");
        formulario.tbpFormulario.remove(formulario.pnlEntrenador);
        formulario.tbpFormulario.remove(formulario.pnlMasajista);
        formulario.tbpFormulario.add("Futbolista", formulario.pnlFutbolista);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Futbolista");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearFutActionPerformed

    private void mnCrearEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearEntActionPerformed
        // Crear Entrenador:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Entrenador");
        formulario.tbpFormulario.remove(formulario.pnlFutbolista);
        formulario.tbpFormulario.remove(formulario.pnlMasajista);
        formulario.tbpFormulario.add("Entrenador", formulario.pnlEntrenador);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Entrenador");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearEntActionPerformed

    private void mnCrearMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearMasActionPerformed
        // Crear Masajista:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Masajista");
        formulario.tbpFormulario.remove(formulario.pnlFutbolista);
        formulario.tbpFormulario.remove(formulario.pnlEntrenador);
        formulario.tbpFormulario.add("Masajista", formulario.pnlMasajista);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Masajista");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearMasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoBuscar;
    private javax.swing.JLabel lblCoincidencia;
    private javax.swing.JLabel lblIdBuscar;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTituloBuscar;
    public javax.swing.JList lstCoincidencia;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenuBar mnBuscar;
    private javax.swing.JMenu mnCrear;
    private javax.swing.JMenuItem mnCrearEnt;
    private javax.swing.JMenuItem mnCrearFut;
    private javax.swing.JMenuItem mnCrearMas;
    private javax.swing.JMenuItem mnOpBuscar;
    private javax.swing.JMenuItem mnOpMostrar;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    public static javax.swing.JTextField txtApellidoBuscar;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables
}
