/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import javax.swing.JOptionPane;
import pkgModelo.clsEntrenador;
import pkgModelo.clsFutbolista;
import pkgModelo.clsMasajista;
import pkgModelo.clsMetodo;
import pkgModelo.clsSeleccionFutbol;
import static pkgVista.frmPrincipal.SeleccionFutbol;

/**
 *
 * @author Richard
 */
public class frmFormulario extends javax.swing.JFrame {

    private static frmFormulario instancia;

    /**
     * Creates new form frmFormulario
     */
    public frmFormulario() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        /*clsMetodo metodo = clsMetodo.getInstance();
         txtId.setText(Integer.toString(metodo.sumaId()));*/
    }

    public static frmFormulario getInstance() {
        if (instancia == null) {
            instancia = new frmFormulario();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        tbpFormulario = new javax.swing.JTabbedPane();
        pnlInicial = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnlFutbolista = new javax.swing.JPanel();
        lblDorsal = new javax.swing.JLabel();
        txtDorsal = new javax.swing.JTextField();
        lblDemarcion = new javax.swing.JLabel();
        txtDemarcion = new javax.swing.JTextField();
        btnGuardarFut = new javax.swing.JButton();
        btnAnteriorFut = new javax.swing.JButton();
        btnLimpiarFutbolista = new javax.swing.JButton();
        pnlEntrenador = new javax.swing.JPanel();
        btnAnteriorEnt = new javax.swing.JButton();
        btnGuardarEnt = new javax.swing.JButton();
        lblFederacion = new javax.swing.JLabel();
        txtFederacion = new javax.swing.JTextField();
        btnLimpiarEntrenador = new javax.swing.JButton();
        pnlMasajista = new javax.swing.JPanel();
        lblTitulacion = new javax.swing.JLabel();
        txtTitulacion = new javax.swing.JTextField();
        txtExperiencia = new javax.swing.JTextField();
        lblExperiencia = new javax.swing.JLabel();
        btnAnteriorMas = new javax.swing.JButton();
        btnGuardarMas = new javax.swing.JButton();
        btnLimpiarMasajista = new javax.swing.JButton();
        lblFormulario = new javax.swing.JLabel();
        mbFormulario = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        mnOpciones = new javax.swing.JMenu();
        mnOpBuscar = new javax.swing.JMenuItem();
        mnOpMostrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblId.setText("Id:");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblApellido.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblApellido.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblFecha.setText("Fecha:");

        btnAnterior.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnAnterior.setText("<-- Menu Inicial");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente-->");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInicialLayout = new javax.swing.GroupLayout(pnlInicial);
        pnlInicial.setLayout(pnlInicialLayout);
        pnlInicialLayout.setHorizontalGroup(
            pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
            .addGroup(pnlInicialLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInicialLayout.createSequentialGroup()
                        .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId)
                            .addComponent(lblApellido)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtId)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInicialLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicialLayout.setVerticalGroup(
            pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        tbpFormulario.addTab("Datos Basicos", pnlInicial);

        lblDorsal.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblDorsal.setText("Dorsal:");

        txtDorsal.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblDemarcion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblDemarcion.setText("Demarción:");

        txtDemarcion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        btnGuardarFut.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnGuardarFut.setText("Guardar");
        btnGuardarFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFutActionPerformed(evt);
            }
        });

        btnAnteriorFut.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnAnteriorFut.setText("<-- Anterior");
        btnAnteriorFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorFutActionPerformed(evt);
            }
        });

        btnLimpiarFutbolista.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnLimpiarFutbolista.setText("Limpiar");
        btnLimpiarFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFutbolistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFutbolistaLayout = new javax.swing.GroupLayout(pnlFutbolista);
        pnlFutbolista.setLayout(pnlFutbolistaLayout);
        pnlFutbolistaLayout.setHorizontalGroup(
            pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFutbolistaLayout.createSequentialGroup()
                .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFutbolistaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDemarcion)
                            .addComponent(lblDorsal))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDorsal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtDemarcion))
                        .addGap(0, 410, Short.MAX_VALUE))
                    .addGroup(pnlFutbolistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnteriorFut)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarFutbolista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarFut)))
                .addContainerGap())
        );
        pnlFutbolistaLayout.setVerticalGroup(
            pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFutbolistaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDorsal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDemarcion)
                    .addComponent(txtDemarcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlFutbolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnteriorFut)
                    .addComponent(btnGuardarFut)
                    .addComponent(btnLimpiarFutbolista))
                .addContainerGap())
        );

        tbpFormulario.addTab("Futbolista", pnlFutbolista);

        btnAnteriorEnt.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnAnteriorEnt.setText("<-- Anterior");
        btnAnteriorEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorEntActionPerformed(evt);
            }
        });

        btnGuardarEnt.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnGuardarEnt.setText("Guardar");
        btnGuardarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEntActionPerformed(evt);
            }
        });

        lblFederacion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblFederacion.setText("Id Federación:");

        txtFederacion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        btnLimpiarEntrenador.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnLimpiarEntrenador.setText("Limpiar");
        btnLimpiarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEntrenadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEntrenadorLayout = new javax.swing.GroupLayout(pnlEntrenador);
        pnlEntrenador.setLayout(pnlEntrenadorLayout);
        pnlEntrenadorLayout.setHorizontalGroup(
            pnlEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntrenadorLayout.createSequentialGroup()
                .addGroup(pnlEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntrenadorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblFederacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFederacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlEntrenadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnteriorEnt)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarEntrenador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                        .addComponent(btnGuardarEnt)))
                .addContainerGap())
        );
        pnlEntrenadorLayout.setVerticalGroup(
            pnlEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntrenadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFederacion)
                    .addComponent(txtFederacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(pnlEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnteriorEnt)
                    .addComponent(btnLimpiarEntrenador)
                    .addComponent(btnGuardarEnt))
                .addContainerGap())
        );

        tbpFormulario.addTab("Entrenador", pnlEntrenador);

        lblTitulacion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblTitulacion.setText("Titulación:");

        txtTitulacion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        txtExperiencia.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        lblExperiencia.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblExperiencia.setText("Años Experiencia:");

        btnAnteriorMas.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnAnteriorMas.setText("<-- Anterior");
        btnAnteriorMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorMasActionPerformed(evt);
            }
        });

        btnGuardarMas.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnGuardarMas.setText("Guardar");
        btnGuardarMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMasActionPerformed(evt);
            }
        });

        btnLimpiarMasajista.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnLimpiarMasajista.setText("Limpiar");
        btnLimpiarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMasajistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMasajistaLayout = new javax.swing.GroupLayout(pnlMasajista);
        pnlMasajista.setLayout(pnlMasajistaLayout);
        pnlMasajistaLayout.setHorizontalGroup(
            pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasajistaLayout.createSequentialGroup()
                .addGroup(pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMasajistaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMasajistaLayout.createSequentialGroup()
                                .addComponent(lblTitulacion)
                                .addGap(18, 18, 18)
                                .addComponent(txtTitulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMasajistaLayout.createSequentialGroup()
                                .addComponent(lblExperiencia)
                                .addGap(18, 18, 18)
                                .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 367, Short.MAX_VALUE))
                    .addGroup(pnlMasajistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnteriorMas)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarMasajista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarMas)))
                .addContainerGap())
        );
        pnlMasajistaLayout.setVerticalGroup(
            pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasajistaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExperiencia)
                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(pnlMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnteriorMas)
                    .addComponent(btnGuardarMas)
                    .addComponent(btnLimpiarMasajista))
                .addContainerGap())
        );

        tbpFormulario.addTab("Masajista", pnlMasajista);

        lblFormulario.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        lblFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mnArchivo.setText("Archivo");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(mnSalir);

        mbFormulario.add(mnArchivo);

        mnOpciones.setText("Opciones");

        mnOpBuscar.setText("Buscar");
        mnOpBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpBuscarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpBuscar);

        mnOpMostrar.setText("Mostrar Todo");
        mnOpMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpMostrarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpMostrar);

        mbFormulario.add(mnOpciones);

        setJMenuBar(mbFormulario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpFormulario)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // Cambiar Pestaña:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        if (metodo.CheckFormulario()== true) {
            tbpFormulario.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Campo Vacio");
            tbpFormulario.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiar Campos Datos Basicos:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEntrenadorActionPerformed
        // Limpiar Campo Entrenador:        
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
    }//GEN-LAST:event_btnLimpiarEntrenadorActionPerformed

    private void btnLimpiarFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFutbolistaActionPerformed
        // Limpiar Campos Futbolista:        
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
    }//GEN-LAST:event_btnLimpiarFutbolistaActionPerformed

    private void btnLimpiarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMasajistaActionPerformed
        // Limpiar Campos Masajista:        
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
    }//GEN-LAST:event_btnLimpiarMasajistaActionPerformed

    private void btnGuardarFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFutActionPerformed
        // Agregar Contacto Futbolista:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        if (metodo.CheckFutbolista() == true) {
            frmPrincipal principal = frmPrincipal.getInstance();
            SeleccionFutbol.add(new clsFutbolista(txtDorsal.getText(), txtDemarcion.getText(), txtId.getText(), txtNombre.getText(), txtApellido.getText(), jcFecha.getDate(), "Futbolista"));
            this.setVisible(false);
            principal.setVisible(true);

            metodo.Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Campo Vacio");
        }
    }//GEN-LAST:event_btnGuardarFutActionPerformed

    private void btnGuardarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEntActionPerformed
        // Agregar Contacto Entrenador:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        if (metodo.CheckEntrenador() == true) {
            frmPrincipal principal = frmPrincipal.getInstance();

            SeleccionFutbol.add(new clsEntrenador(txtFederacion.getText(), txtId.getText(), txtNombre.getText(), txtApellido.getText(), jcFecha.getDate(), "Entrenador"));
            this.setVisible(false);
            principal.setVisible(true);

            metodo.Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Campo Vacio");
        }
    }//GEN-LAST:event_btnGuardarEntActionPerformed

    private void btnGuardarMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMasActionPerformed
        // Agregar Contacto Masajista:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        if (metodo.CheckMasajista() == true) {
            frmPrincipal principal = frmPrincipal.getInstance();

            SeleccionFutbol.add(new clsMasajista(txtTitulacion.getText(), txtExperiencia.getText(), txtId.getText(), txtNombre.getText(), txtApellido.getText(), jcFecha.getDate(), "Masajista"));
            this.setVisible(false);
            principal.setVisible(true);

            metodo.Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Campo Vacio");
        }
    }//GEN-LAST:event_btnGuardarMasActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // Volver Menu Principal:
        frmPrincipal principal = frmPrincipal.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        metodo.Limpiar();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAnteriorFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorFutActionPerformed
        // Volver a Datos Basicos:
        tbpFormulario.setSelectedIndex(0);
    }//GEN-LAST:event_btnAnteriorFutActionPerformed

    private void btnAnteriorEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorEntActionPerformed
        // Volver a Datos Basicos:
        tbpFormulario.setSelectedIndex(0);
    }//GEN-LAST:event_btnAnteriorEntActionPerformed

    private void btnAnteriorMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorMasActionPerformed
        // Volver a Datos Basicos:
        tbpFormulario.setSelectedIndex(0);
    }//GEN-LAST:event_btnAnteriorMasActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // Salir de la Aplicacion:
        dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnOpBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpBuscarActionPerformed
        // Buscar:
        pkgVista.frmBuscar buscar = frmBuscar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            buscar.lstCoincidencia.setModel(metodo.Listar());
            buscar.setTitle("Buscar");
            buscar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }
    }//GEN-LAST:event_mnOpBuscarActionPerformed

    private void mnOpMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpMostrarActionPerformed
        // mostrar Todo:
        pkgVista.frmMostrar mostrar = frmMostrar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            frmMostrar.lstMostar.setModel(metodo.Listar());
            mostrar.setTitle("Mostrar Selección");
            mostrar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }
    }//GEN-LAST:event_mnOpMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAnteriorEnt;
    private javax.swing.JButton btnAnteriorFut;
    private javax.swing.JButton btnAnteriorMas;
    private javax.swing.JButton btnGuardarEnt;
    private javax.swing.JButton btnGuardarFut;
    private javax.swing.JButton btnGuardarMas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarEntrenador;
    private javax.swing.JButton btnLimpiarFutbolista;
    private javax.swing.JButton btnLimpiarMasajista;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollBar jScrollBar1;
    public com.toedter.calendar.JDateChooser jcFecha;
    public javax.swing.JLabel lblApellido;
    public javax.swing.JLabel lblDemarcion;
    public javax.swing.JLabel lblDorsal;
    public javax.swing.JLabel lblExperiencia;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblFederacion;
    public javax.swing.JLabel lblFormulario;
    public javax.swing.JLabel lblId;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblTitulacion;
    private javax.swing.JMenuBar mbFormulario;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenuItem mnOpBuscar;
    private javax.swing.JMenuItem mnOpMostrar;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    public javax.swing.JPanel pnlEntrenador;
    public javax.swing.JPanel pnlFutbolista;
    public javax.swing.JPanel pnlInicial;
    public javax.swing.JPanel pnlMasajista;
    public javax.swing.JTabbedPane tbpFormulario;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtDemarcion;
    public javax.swing.JTextField txtDorsal;
    public javax.swing.JTextField txtExperiencia;
    public javax.swing.JTextField txtFederacion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTitulacion;
    // End of variables declaration//GEN-END:variables
}
