/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import javax.swing.JOptionPane;
import pkgModelo.clsMetodo;

/**
 *
 * @author Richard
 */
public class frmMostrar extends javax.swing.JFrame {

    private static frmMostrar instancia;

    /**
     * Creates new form frmMostrar
     */
    public frmMostrar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    public static frmMostrar getInstance() {
        if (instancia == null) {
            instancia = new frmMostrar();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMostrar = new javax.swing.ButtonGroup();
        pnlMostar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMostar = new javax.swing.JList();
        lblMostrar = new javax.swing.JLabel();
        lblTituloMostrar = new javax.swing.JLabel();
        btnManuPrincipal = new javax.swing.JButton();
        radiobtnFutbolista = new javax.swing.JRadioButton();
        radiobtnEntrenador = new javax.swing.JRadioButton();
        radiobtnMasajistas = new javax.swing.JRadioButton();
        radiobtnTodo = new javax.swing.JRadioButton();
        mnListar = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        mnOpciones = new javax.swing.JMenu();
        mnOpBuscar = new javax.swing.JMenuItem();
        mnOpMostrar = new javax.swing.JMenuItem();
        mnCrear = new javax.swing.JMenu();
        mnCrearFut = new javax.swing.JMenuItem();
        mnCrearEnt = new javax.swing.JMenuItem();
        mnCrearMas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMostar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lstMostar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstMostar);

        lblMostrar.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        lblMostrar.setText("Seleccione una Opción:");

        lblTituloMostrar.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        lblTituloMostrar.setText("Mostrar Seleccion de Futbol");

        btnManuPrincipal.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnManuPrincipal.setText("<-- Menú Principal");
        btnManuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuPrincipalActionPerformed(evt);
            }
        });

        btnGroupMostrar.add(radiobtnFutbolista);
        radiobtnFutbolista.setFont(new java.awt.Font("Century Schoolbook", 0, 13)); // NOI18N
        radiobtnFutbolista.setText("Mostrar Futbolistas");
        radiobtnFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnFutbolistaActionPerformed(evt);
            }
        });

        btnGroupMostrar.add(radiobtnEntrenador);
        radiobtnEntrenador.setFont(new java.awt.Font("Century Schoolbook", 0, 13)); // NOI18N
        radiobtnEntrenador.setText("Mostrar Entrenadores");
        radiobtnEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnEntrenadorActionPerformed(evt);
            }
        });

        btnGroupMostrar.add(radiobtnMasajistas);
        radiobtnMasajistas.setFont(new java.awt.Font("Century Schoolbook", 0, 13)); // NOI18N
        radiobtnMasajistas.setText("Mostrar Masajistas");
        radiobtnMasajistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMasajistasActionPerformed(evt);
            }
        });

        btnGroupMostrar.add(radiobtnTodo);
        radiobtnTodo.setFont(new java.awt.Font("Century Schoolbook", 0, 13)); // NOI18N
        radiobtnTodo.setText("Mostrar Todo");
        radiobtnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMostarLayout = new javax.swing.GroupLayout(pnlMostar);
        pnlMostar.setLayout(pnlMostarLayout);
        pnlMostarLayout.setHorizontalGroup(
            pnlMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMostarLayout.createSequentialGroup()
                        .addComponent(btnManuPrincipal)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMostarLayout.createSequentialGroup()
                        .addGroup(pnlMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtnEntrenador)
                            .addComponent(radiobtnTodo)
                            .addComponent(radiobtnFutbolista)
                            .addComponent(radiobtnMasajistas)
                            .addComponent(lblMostrar))
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMostarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloMostrar)
                .addGap(124, 124, 124))
        );
        pnlMostarLayout.setVerticalGroup(
            pnlMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMostrar)
                .addGroup(pnlMostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMostarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMostrar)
                        .addGap(26, 26, 26)
                        .addComponent(radiobtnTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtnFutbolista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtnEntrenador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobtnMasajistas)
                        .addGap(42, 42, 42)
                        .addComponent(btnManuPrincipal)
                        .addContainerGap())
                    .addGroup(pnlMostarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        mnArchivo.setText("Archivo");

        mnSalir.setText("Salir");
        mnArchivo.add(mnSalir);

        mnListar.add(mnArchivo);

        mnOpciones.setText("Opciones");

        mnOpBuscar.setText("Buscar");
        mnOpBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpBuscarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpBuscar);

        mnOpMostrar.setText("Mostrar Todo");
        mnOpMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpMostrarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpMostrar);

        mnListar.add(mnOpciones);

        mnCrear.setText("Crear");

        mnCrearFut.setText("Crear Futbolista");
        mnCrearFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearFutActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearFut);

        mnCrearEnt.setText("Crear Entrenador");
        mnCrearEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearEntActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearEnt);

        mnCrearMas.setText("Crear Masajista");
        mnCrearMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearMasActionPerformed(evt);
            }
        });
        mnCrear.add(mnCrearMas);

        mnListar.add(mnCrear);

        setJMenuBar(mnListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuPrincipalActionPerformed
        // Volver Menu Principal:
        frmPrincipal principal = frmPrincipal.getInstance();

        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_btnManuPrincipalActionPerformed

    private void radiobtnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnTodoActionPerformed
        // Mostrar Todo
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        this.setTitle("Seleccion Futbol");
        lstMostar.setModel(metodo.Listar());
    }//GEN-LAST:event_radiobtnTodoActionPerformed

    private void radiobtnFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnFutbolistaActionPerformed
        // Mostrar Futbolistas:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        this.setTitle("Futbolistas");
        lstMostar.setModel(metodo.ListarFutbolista());
    }//GEN-LAST:event_radiobtnFutbolistaActionPerformed

    private void radiobtnEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnEntrenadorActionPerformed
        // Mostrar Entrenador:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        this.setTitle("Entrenadores");
        lstMostar.setModel(metodo.ListarEntrenador());
    }//GEN-LAST:event_radiobtnEntrenadorActionPerformed

    private void radiobtnMasajistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMasajistasActionPerformed
        // Mostrar Masajistas:
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();

        this.setTitle("Masajistas");
        lstMostar.setModel(metodo.ListarMasajista());
    }//GEN-LAST:event_radiobtnMasajistasActionPerformed

    private void mnOpBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpBuscarActionPerformed
        // Buscar:
        pkgVista.frmBuscar buscar = frmBuscar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            buscar.lstCoincidencia.setModel(metodo.Listar());
            buscar.setTitle("Buscar");
            buscar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }
    }//GEN-LAST:event_mnOpBuscarActionPerformed

    private void mnOpMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpMostrarActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_mnOpMostrarActionPerformed

    private void mnCrearFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearFutActionPerformed
        // Crear Futbolista:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Futbolista");
        formulario.tbpFormulario.remove(formulario.pnlEntrenador);
        formulario.tbpFormulario.remove(formulario.pnlMasajista);
        formulario.tbpFormulario.add("Futbolista", formulario.pnlFutbolista);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Futbolista");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearFutActionPerformed

    private void mnCrearEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearEntActionPerformed
        // Crear Entrenador:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Entrenador");
        formulario.tbpFormulario.remove(formulario.pnlFutbolista);
        formulario.tbpFormulario.remove(formulario.pnlMasajista);
        formulario.tbpFormulario.add("Entrenador", formulario.pnlEntrenador);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Entrenador");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearEntActionPerformed

    private void mnCrearMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearMasActionPerformed
        // Crear Masajista:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        formulario.setTitle("Masajista");
        formulario.tbpFormulario.remove(formulario.pnlFutbolista);
        formulario.tbpFormulario.remove(formulario.pnlEntrenador);
        formulario.tbpFormulario.add("Masajista", formulario.pnlMasajista);
        formulario.tbpFormulario.setSelectedIndex(0);
        formulario.txtId.setText(Integer.toString(metodo.sumaId()));
        formulario.lblFormulario.setText("Crear Masajista");
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCrearMasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupMostrar;
    private javax.swing.JButton btnManuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblTituloMostrar;
    public static javax.swing.JList lstMostar;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnCrear;
    private javax.swing.JMenuItem mnCrearEnt;
    private javax.swing.JMenuItem mnCrearFut;
    private javax.swing.JMenuItem mnCrearMas;
    private javax.swing.JMenuBar mnListar;
    private javax.swing.JMenuItem mnOpBuscar;
    private javax.swing.JMenuItem mnOpMostrar;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JPanel pnlMostar;
    private javax.swing.JRadioButton radiobtnEntrenador;
    private javax.swing.JRadioButton radiobtnFutbolista;
    private javax.swing.JRadioButton radiobtnMasajistas;
    private javax.swing.JRadioButton radiobtnTodo;
    // End of variables declaration//GEN-END:variables
}
