/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import pkgExportar.ModeloExcel;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pkgModelo.clsMetodo;
import pkgModelo.clsSeleccionFutbol;

/**
 *
 * @author Richard
 */
public class frmPrincipal extends javax.swing.JFrame {

    public static ArrayList<clsSeleccionFutbol> SeleccionFutbol = new ArrayList<>();
    private static frmPrincipal instancia;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public static frmPrincipal getInstance() {
        if (instancia == null) {
            instancia = new frmPrincipal();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        cmbMenu = new javax.swing.JComboBox();
        btnMostrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Century Schoolbook", 0, 48)); // NOI18N
        lblTitulo.setText("Selección de Futbol");

        lblMenu.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        lblMenu.setText("Selecione una Opción:");

        cmbMenu.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        cmbMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Crear Futbolista...", "Crear Entrenador...", "Crear Masajista", " " }));
        cmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenuActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnMostrar.setText("Mostrar Todo");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar Excel");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportar))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblMenu)
                        .addGap(34, 34, 34)
                        .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(131, 131, 131))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(68, 68, 68)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnExportar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenuActionPerformed
        // ComboBox Menu Princial:
        frmFormulario formulario = frmFormulario.getInstance();
        clsMetodo metodo = clsMetodo.getInstance();

        switch (cmbMenu.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Elija una opcion valida");
                this.setVisible(true);
                formulario.setVisible(false);
                break;
            case 1:
                formulario.setTitle("Futbolista");
                formulario.tbpFormulario.remove(formulario.pnlEntrenador);
                formulario.tbpFormulario.remove(formulario.pnlMasajista);
                formulario.tbpFormulario.add("Futbolista", formulario.pnlFutbolista);
                formulario.txtId.setText(Integer.toString(metodo.sumaId()));
                formulario.tbpFormulario.setSelectedIndex(0);
                formulario.lblFormulario.setText("Crear Futbolista");
                formulario.setVisible(true);
                this.setVisible(false);
                break;
            case 2:
                formulario.setTitle("Entrenador");
                formulario.tbpFormulario.remove(formulario.pnlFutbolista);
                formulario.tbpFormulario.remove(formulario.pnlMasajista);
                formulario.tbpFormulario.add("Entrenador", formulario.pnlEntrenador);
                formulario.txtId.setText(Integer.toString(metodo.sumaId()));
                formulario.tbpFormulario.setSelectedIndex(0);
                formulario.lblFormulario.setText("Crear Entrenador");
                formulario.setVisible(true);
                this.setVisible(false);
                break;
            case 3:
                formulario.setTitle("Masajista");
                formulario.tbpFormulario.remove(formulario.pnlFutbolista);
                formulario.tbpFormulario.remove(formulario.pnlEntrenador);
                formulario.tbpFormulario.add("Masajista", formulario.pnlMasajista);
                formulario.txtId.setText(Integer.toString(metodo.sumaId()));
                formulario.tbpFormulario.setSelectedIndex(0);
                formulario.lblFormulario.setText("Crear Masajista");
                formulario.setVisible(true);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_cmbMenuActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // mostrar Todo:
        pkgVista.frmMostrar mostrar = frmMostrar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            frmMostrar.lstMostar.setModel(metodo.Listar());
            mostrar.setTitle("Mostrar Selección");
            mostrar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }

    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Buscar:
        pkgVista.frmBuscar buscar = frmBuscar.getInstance();
        pkgModelo.clsMetodo metodo = clsMetodo.getInstance();
        if (metodo.Array() == true) {
            buscar.lstCoincidencia.setModel(metodo.Listar());
            buscar.setTitle("Buscar");
            buscar.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Ningun Registro en la Selecion de Futbol");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        //Exportar a Excel
        JFileChooser selecArchivo = new JFileChooser();
        ModeloExcel modeloE = new ModeloExcel();
        File archivo;
        selecArchivo.setSelectedFile(new File("Seleccion de Futbol.xls"));
        if (selecArchivo.showDialog(null, "Exportar") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                JOptionPane.showMessageDialog(null, modeloE.Exportar(archivo) + "\n Formato ." + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cmbMenu;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
